inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1.10

Metrics/AbcSize:
  Max: 27

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false
